-- The tracker's complete schema, as one file.
--
-- This replaces a seven-file migration history (0001_baseline through
-- 0007_add_search_runs) that had accumulated for a bad reason. The original
-- baseline used CREATE TABLE IF NOT EXISTS against a database whose tables
-- already existed from a hand-run schema, so its column list silently did
-- nothing, and 0002 had to re-add those same columns for real with ALTER
-- TABLE. That left the repo unable to set up a fresh database at all: on an
-- empty D1, the baseline created the columns and then 0002 died on
-- "duplicate column name: team", taking the whole deploy with it. Every
-- later migration was stranded behind that failure.
--
-- Consolidating is safe here because there has only ever been one
-- deployment. There is no other installation whose database needs the old
-- files to reach this state, so nothing is lost by collapsing them, and the
-- accumulated ALTER history was describing a migration path no database will
-- ever walk again.
--
-- The existing deployment was NOT rebuilt to match this file. Its tables
-- already hold this exact set of columns with these types and constraints;
-- they just carry them in the physical order the old ALTERs appended them,
-- which SQLite cannot change without recreating the table. Nothing depends
-- on column order - every INSERT in src/db.js names its columns, and every
-- SELECT * is consumed as a keyed object - so the two are equivalent in
-- every way that affects behaviour. This file is the authority on what
-- columns exist; it is not a byte-for-byte transcript of the live table.
--
-- Migrations continue from here: the next schema change is 0002_<name>.sql
-- created with `wrangler d1 migrations create job-search-tracker-db <name>`,
-- using real ALTER TABLE statements. Do not edit this file to add a column -
-- against any database that already ran it, an edit here is a no-op, which
-- is the exact trap that produced the history this file replaces.

-- One row per job posting the search found and verified live.
CREATE TABLE IF NOT EXISTS leads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  search TEXT NOT NULL,               -- track key, matches tracks.key
  found TEXT NOT NULL,                -- date first found, YYYY-MM-DD
  company TEXT NOT NULL,
  title TEXT NOT NULL,
  location TEXT NOT NULL DEFAULT '',
  url TEXT NOT NULL,
  verified TEXT NOT NULL,             -- date last verified live, YYYY-MM-DD
  fit TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'New', -- LEAD_STATUS in src/routes/leads.js
  notes TEXT NOT NULL DEFAULT '',
  -- Whether the original posting has been confirmed taken down. Deliberately
  -- separate from `status`, which is the installer's own application
  -- progress: a lead can be "Applied" and delisted at once without either
  -- overwriting the other. '' = still live (or not re-checked yet); a
  -- YYYY-MM-DD = the day a search confirmed it gone. Cleared back to '' if a
  -- later check finds it live again.
  delistedOn TEXT NOT NULL DEFAULT '',
  -- Freeform fields shared with `applications` (EXTRA_FIELDS in src/db.js),
  -- so a referral or comp note jotted on a posting survives it becoming an
  -- application. The search only ever fills team/setup/comp - the ones a
  -- posting can actually state; the rest are the installer's own.
  team TEXT NOT NULL DEFAULT '',
  setup TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT '',
  link TEXT NOT NULL DEFAULT '',
  lastContact TEXT NOT NULL DEFAULT '',
  nextAction TEXT NOT NULL DEFAULT '',
  nextActionDate TEXT NOT NULL DEFAULT '',
  resume TEXT NOT NULL DEFAULT '',
  referral TEXT NOT NULL DEFAULT '',
  comp TEXT NOT NULL DEFAULT '',
  -- Lets adding leads use INSERT OR IGNORE for atomic, race-free dedup.
  UNIQUE(search, url)
);

-- One row per job actually applied to. Created automatically when a lead
-- moves to "Applied" (see handleSetLeadStatus), or added by hand.
CREATE TABLE IF NOT EXISTS applications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  leadId TEXT NOT NULL DEFAULT '',    -- the originating leads.id, as text; '' if added by hand
  company TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  dateApplied TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Applied',  -- APP_STATUS in src/routes/applications.js
  notes TEXT NOT NULL DEFAULT '',
  -- Same freeform block as leads above.
  team TEXT NOT NULL DEFAULT '',
  setup TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT '',
  link TEXT NOT NULL DEFAULT '',
  lastContact TEXT NOT NULL DEFAULT '',
  nextAction TEXT NOT NULL DEFAULT '',
  nextActionDate TEXT NOT NULL DEFAULT '',
  resume TEXT NOT NULL DEFAULT '',
  referral TEXT NOT NULL DEFAULT '',
  comp TEXT NOT NULL DEFAULT '',
  -- When this application first reached each pipeline stage - not an
  -- append-only history of every status click, just "when did it first get
  -- here". Stamped once on the status change that reaches the stage, then
  -- editable by hand so a missed day can be corrected or a skipped stage
  -- backfilled. "Applied" isn't here; it has dateApplied above.
  dateRecruiterScreen TEXT NOT NULL DEFAULT '',
  dateTechScreen TEXT NOT NULL DEFAULT '',
  dateOnsite TEXT NOT NULL DEFAULT '',
  dateOffer TEXT NOT NULL DEFAULT '',
  dateRejected TEXT NOT NULL DEFAULT '',
  dateWithdrawn TEXT NOT NULL DEFAULT ''
);

-- Postings the search looked at and deliberately did NOT add as a lead:
-- dead on arrival, out of scope, wrong level, or a duplicate. Distinct from
-- leads.delistedOn, which is about a lead that WAS added and later died.
-- Exists so tomorrow's run doesn't re-spend a verification attempt on
-- something already ruled out. No delete/un-screen route: a screening
-- decision is expected to stay true.
CREATE TABLE IF NOT EXISTS screened (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  search TEXT NOT NULL,               -- track key, matches tracks.key
  url TEXT NOT NULL,
  company TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  location TEXT NOT NULL DEFAULT '',
  reason TEXT NOT NULL DEFAULT '',    -- free text, e.g. "outside the US: London, UK", "below target level"
  date TEXT NOT NULL,                 -- date screened, YYYY-MM-DD
  UNIQUE(search, url)                 -- same dedup pattern as leads
);

-- The tracks the installer searches for - one row per track tab on the page.
-- Config, not content: this is what lets one deployment of this code serve
-- any installer's job search without editing the client. Written by
-- POST /api/config (the job-search-setup skill posts it during onboarding).
CREATE TABLE IF NOT EXISTS tracks (
  key TEXT PRIMARY KEY,               -- e.g. "SWE"; matches leads.search
  label TEXT NOT NULL,                -- the tab label, e.g. "Engineering"
  full_description TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0
);

-- One row per track: when that track's scheduled search last ran, and what
-- it did. Kept 1:1 with `tracks` by handleSetConfig. This is the only thing
-- that can tell "the search ran and genuinely found nothing" apart from "the
-- search stopped running" - a run that finds nothing writes nothing else
-- anywhere, so without it a search that quietly broke looks like a normal
-- quiet day. Written by POST /api/runs, which the scheduled search calls
-- unconditionally at the end of every run.
--
-- Last-run-only, not a run history: the question the UI asks is "is this
-- still running?", which only ever needs the newest answer.
CREATE TABLE IF NOT EXISTS search_runs (
  track_key TEXT PRIMARY KEY,             -- matches tracks.key
  last_run_at TEXT NOT NULL DEFAULT '',   -- ISO 8601 UTC instant. '' = never recorded.
  -- The caller's LOCAL date. The worker only knows UTC, but "did it run this
  -- morning?" is a question about the installer's day - a 08:00 Pacific run
  -- is already the next UTC date, so deriving this from last_run_at would
  -- display tomorrow. last_run_at stays the instant used for staleness math.
  last_run_on TEXT NOT NULL DEFAULT '',   -- YYYY-MM-DD
  status TEXT NOT NULL DEFAULT '',        -- 'ok' | 'error'
  leads_added INTEGER NOT NULL DEFAULT 0,
  screened_added INTEGER NOT NULL DEFAULT 0,
  delisted INTEGER NOT NULL DEFAULT 0,
  note TEXT NOT NULL DEFAULT ''           -- short human summary, or the error
);

-- Key/value settings: 'updated' (last data change, YYYY-MM-DD) plus the
-- display config read by getTracksAndSettings - display_title,
-- overview_label, applications_label, stale_run_hours, and
-- priority_locations (a JSON array of ordered location-matching rules).
-- All optional: src/db.js's DEFAULT_SETTINGS covers anything absent, which
-- is what lets a freshly created database serve a usable page before setup
-- has posted any config.
CREATE TABLE IF NOT EXISTS meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- No seed data on purpose. The superseded 0003 seeded one specific person's
-- tracks and page title so their existing deployment wouldn't visibly change
-- mid-migration; that transition is long finished, and baking those values
-- into the schema would hand every new installation someone else's job
-- search to look at. A new database starts empty and gets its tracks and
-- settings from POST /api/config, which is what the job-search-setup skill
-- does during onboarding.
