-- Whether a lead's original posting has been confirmed taken down - kept
-- separate from `status` (the installer's own application-progress field:
-- New/Reviewing/Applied/Closed/etc.) so a lead can be "Applied" and delisted
-- at the same time without either overwriting the other. A dead posting
-- used to mean the search retired the whole lead from view; now it's just
-- a fact recorded alongside whatever the installer has done with it.
--
-- Empty string = still live (or not yet re-checked since being added).
-- A YYYY-MM-DD date = the day a scheduled search confirmed the posting was
-- no longer live. Cleared back to '' if a later check finds it live again.
ALTER TABLE leads ADD COLUMN delistedOn TEXT NOT NULL DEFAULT '';
