-- Lets an application be added as nothing but a URL, and filled in overnight.
--
-- Adding an application by hand is nine empty fields, and the person filling
-- them is copying every one of them off a posting they have open in the next
-- tab. The URL is the only part of that they can't derive - so this makes the
-- URL the whole of what they have to enter, and hands the copying to the same
-- nightly Claude run that already opens and reads job postings for the search
-- tabs (see src/prompt.js's buildAutofillPrompt, and the `_applications`
-- reserved key in src/routes/index.js).
--
-- `autofill` is bookkeeping, not a status. The page renders nothing from it
-- except the one case that needs answering (see below): an application either
-- has its company and role in it or it doesn't, and that is all the person
-- needs to see while this is working. The column exists for one reason - so a
-- row is looked at once and then left alone.
--
--   ''        not looked at yet (also every row that never needed looking at)
--   'filled'  a run read the posting and wrote down what it said
--   'failed'  a run opened it and couldn't - `autofill_note` says why
--
-- Which rows a run looks at is derived rather than requested: any application
-- with a link, still flagged '', that is missing a company, a role or a
-- location (see db.js's getAutofillQueue). Nothing has to be queued, marked or
-- asked for, at creation or afterwards - so there is no state the page could
-- set wrong, and nothing to remember to do. A row created from a lead already
-- carries all three, so it is never fetched; a row pasted in as a URL is
-- missing all three, so it is.
--
-- One look per row, either way. That is what the flag buys, and it is why
-- 'failed' is not retried: the failures that actually happen here - a posting
-- already taken down, a login wall, a domain that refuses automated fetches -
-- are the ones a retry doesn't fix, and a row that kept its place in the queue
-- would be re-fetched every night forever without anything ever saying so. A
-- posting nobody could read leaves the fields blank, which is the same thing
-- the person would have seen if this feature didn't exist; they type it in.
--
-- `autofill_note` is that reason, kept out of `notes` rather than appended to
-- it. `notes` is the person's own field, written back wholesale by every edit
-- on the page, so a run writing into it would race the textarea they may be
-- typing in - and would put a machine's apology inside the one column that is
-- theirs.
--
-- This one *is* shown, on the row it belongs to, and it is the only thing
-- about the fill that ever appears on the page. A 'failed' row is the row
-- nothing is coming for: without saying so it looks exactly like one that
-- hasn't been read yet, and the person waits for a fill that will never
-- happen. The reason is what makes that actionable - "the posting has been
-- taken down" and "the domain blocks automated fetches" call for different
-- things from the reader.
ALTER TABLE applications ADD COLUMN autofill TEXT NOT NULL DEFAULT '';
ALTER TABLE applications ADD COLUMN autofill_note TEXT NOT NULL DEFAULT '';
